version: "3.1"

services:
  db:
    image: postgres:14.2-alpine
    restart: always
    container_name: myStock-db
    environment:
      POSTGRES_USER: myStock-db
      POSTGRES_PASSWORD: myStock-db
      POSTGRES_DB: myStock-db
      PGDATA: /var/lib/postgresql/data/myStock-db
    ports:
      - "5432:5432"
    tty: true
    networks:
      - mystock-db

networks:
  mystock-db:
